name: CI

on:
  push:
    branches: 'main'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare build
        id: prepare
        run: |
          DOCKER_IMAGE=ghcr.io/${GITHUB_REPOSITORY}
          VERSION="${GITHUB_REF#refs/*/}-${GITHUB_SHA:0:8}"
          TAGS="${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:latest"
          echo ::set-output name=tags::${TAGS}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: '${{ steps.prepare.outputs.tags }}'
